language: generic
os: osx
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - cmake
            - g++-5
          sources: &sources
            - ubuntu-toolchain-r-test
    - os: linux
      dist: trusty
      sudo: false
      env: COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6
      addons:
        apt:
          packages:
            - cmake
            - g++-6
          sources: *sources
    - os: linux
      dist: trusty
      sudo: false
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - cmake
            - g++-5
            - clang-3.8
          sources: *sources
script:
  - cmake --version
  - ${CXX} --version || true
  - cmake .
  - make -j2